name: verify changes

on:
  push:
    paths:
      - '**.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: flake8
      run: |
        pip install flake8
        flake8 --count --show-source --statistics
    - name: isort
      run: |
        pip install isort
        isort -c lodimp
    - name: mypy
      run: |
        pip install mypy
        mypy -p lodimp
    - name: pytest
      run: |
        pip install pytest pytest-mock
        pytest tests
